# Generated by Django 4.1.3 on 2023-07-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=233)),
                ('category', models.CharField(choices=[('job', 'Job Issues'), ('school', 'School'), ('family', 'Family'), ('daily_acts', 'Daily Routine'), ('vacation', 'Vacation & Weekends'), ('business', 'My Business'), ('others', 'Others')], default='daily_acts', max_length=80)),
                ('due_date', models.DateField(auto_now=True)),
                ('description', tinymce.models.HTMLField()),
                ('is_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('due_date',),
            },
        ),
    ]
