# Generated by Django 4.1.3 on 2023-04-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='is_popular',
            field=models.BooleanField(default=True),
        ),
    ]
