# Generated by Django 4.1.3 on 2023-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
