# Generated by Django 4.1.3 on 2023-03-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp1', '0004_alter_post_options_rename_post_comment_posting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='posting',
            new_name='post',
        ),
    ]
