# Generated by Django 4.1.3 on 2023-08-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='category',
            field=models.CharField(choices=[('laptops', 'Laptops'), ('phones', 'Phones'), ('gadgets', 'Gadgets')], default='laptops', max_length=60),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
