# Generated by Django 4.1.3 on 2023-04-13 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recapblog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=233)),
                ('content', models.TextField()),
                ('email', models.EmailField(default='your_email@you.co', max_length=254)),
                ('company', models.URLField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('apost', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commented', to='recapblog.post')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
