# Generated by Django 4.1.3 on 2023-04-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapblog', '0003_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
