# Generated by Django 4.1.3 on 2023-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recapblog', '0005_remove_post_status_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
